export const models = [
 {id:'eon',name:'EON',character:'ESSENTIAL',tagline:'Everyday, electrified.',description:'A sharp, contemporary companion for the office commute and everyday city rides.',image:'/images/zeno.webp',explodedVideo:'/videos/involt/EON_logo.mp4',imageWidth:1280,imageHeight:1078,referenceColor:'#c31817',voltage:'48V / 60V / 72V',kind:'sport'},
 {id:'plusex',name:'PluseX',character:'SPORT',tagline:'A little more attitude.',description:'A sculpted, sporty design. The brochure positions PluseX for a stronger pickup feel and a sporty ride.',image:'/images/urbanx.webp',explodedVideo:'/videos/involt/PluseX_logo.mp4',imageWidth:1280,imageHeight:992,referenceColor:'#f2f3ef',voltage:'48V / 60V / 72V',kind:'sport'},
 {id:'activex',name:'ActiveX',character:'DYNAMIC',tagline:'Move with purpose.',description:'Angular lines and a practical step-through layout for your daily office commute.',image:'/images/vibe.webp',explodedVideo:'/videos/involt/ActiveX_logo.mp4',imageWidth:1280,imageHeight:1175,referenceColor:'#666967',voltage:'60V / 72V',kind:'angular'},
 {id:'urbanx',name:'UrbanX',character:'CITY',tagline:'At home in the city.',description:'A rounded silhouette and passenger backrest bring a relaxed character to everyday mobility.',image:'/images/plusex.webp',explodedVideo:'/videos/involt/UrbanX_logo.mp4',imageWidth:1280,imageHeight:1109,referenceColor:'#777a6b',voltage:'60V / 72V',kind:'classic'},
 {id:'vibe',name:'Vibe',character:'CLASSIC',tagline:'Classic soul. Electric heart.',description:'A rounded headlamp, flowing bodywork and timeless scooter proportions, reimagined for an electric ride.',image:'/images/activex.webp',explodedVideo:'/videos/involt/Vibe_logo.mp4',imageWidth:1280,imageHeight:1150,referenceColor:'#a2a4a1',voltage:'60V / 72V',kind:'retro'},
 {id:'zeno',name:'Zeno',character:'MODERN',tagline:'A fresh kind of freedom.',description:'A clean, geometric profile with an open step-through design and passenger backrest.',image:'/images/eon.webp',explodedVideo:'/videos/involt/ZENO_logo.mp4',imageWidth:1280,imageHeight:1071,referenceColor:'#8c9c80',voltage:'60V / 72V',kind:'minimal'},
];
export type Model = typeof models[number];
export const colors = [{name:'White',hex:'#eef0e9'},{name:'Maroon',hex:'#a41625'},{name:'Matt Army Green',hex:'#747d58'},{name:'Grey',hex:'#71787d'},{name:'Black',hex:'#202326'}];
export function specifications(model:Model){return [
 ['Motor','BLDC (waterproof)'],['Voltage',model.voltage],['Speed','25 km/h'],['Riding modes','Eco / City / Turbo'],['Speedometer','LED digital'],['Climbing capacity','19°'],['Front suspension','Hydraulic telescopic'],['Rear suspension','Hydraulic dual spring shockers'],['Tyres & wheels','12-inch alloy wheels · 90/90-12 tyres (front and rear)'],['Headlight','LED'],['Ground clearance','190 mm'],['Weight','58 kg (excluding battery)'],['Registration & licence','Not required — as stated in brochure'],['Battery options','Lead acid & graphene: 28 Ah / 32 Ah / 36 Ah; NMC: 25 Ah / 30 Ah'],['Charger','3 Amp / 4 Amp / 6 Amp'],['Charging time','6–8 hours / 3–4 hours'],['Brake system','Front & rear disc with E-ABS']
];}
