'use client';
import {useState} from 'react';import {useSearchParams} from 'next/navigation';import Link from 'next/link';import {ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';import {Switch} from '@/components/ui/switch';import VehicleViewer from '@/components/vehicle-viewer';import {models,colors} from '@/lib/models';
export default function Studio(){
 const search=useSearchParams();const requested=search.get('model');const initial=models.find(m=>m.id===requested)??models[0];const[selected,setSelected]=useState(initial.id);const[color,setColor]=useState(initial.referenceColor);const[auto,setAuto]=useState(false);const[angle,setAngle]=useState('side');const[angleKey,setAngleKey]=useState(0);const[viewerStatus,setViewerStatus]=useState<'loading'|'ready'|'error'>('loading');
 const model=models.find(m=>m.id===selected)!;const chooseAngle=(a:string)=>{setAuto(false);setAngle(a);setAngleKey(k=>k+1);};
 const chooseModel=(id:string)=>{const next=models.find(m=>m.id===id)!;setSelected(id);setColor(next.referenceColor);};
 return <><div className="page-intro"><div><p className="eyebrow">THE INTERACTIVE SHOWROOM</p><h1>Every angle.<br className="mobile-break"/> <em>All yours.</em></h1></div><p>Pick a model. Choose a colour.<br/>Take a closer look at what moves you.</p></div><section className="studio-page"><Tabs value={selected} onValueChange={chooseModel}><TabsList className="model-tabs" aria-label="Choose a 3D model">{models.map(m=><TabsTrigger key={m.id} value={m.id}>{m.name}</TabsTrigger>)}</TabsList><TabsContent value={selected} key="viewer" className="studio-layout"><VehicleViewer model={model} color={color} autoRotate={auto} angle={angle} angleKey={angleKey} onStatus={setViewerStatus}/><aside className="viewer-sidebar"><div><p className="eyebrow">{model.character} / ELECTRIC</p><h2>{model.name}</h2><p>{model.tagline}</p></div><div><label className="control-label" id="color-label">Finish <span>{colors.find(c=>c.hex===color)?.name??'Reference finish'}</span></label><RadioGroup className="viewer-colors" value={color} onValueChange={setColor} aria-labelledby="color-label"><RadioGroupItem disabled={viewerStatus!=='ready'} value={model.referenceColor} style={{background:model.referenceColor}} aria-label={'Reference '+model.name+' finish'} title="Reference finish"/>{colors.filter(c=>c.hex!==model.referenceColor).map(c=><RadioGroupItem disabled={viewerStatus!=='ready'} key={c.name} value={c.hex} style={{background:c.hex}} aria-label={c.name} title={c.name}/>)}</RadioGroup></div><div><span className="control-label">Quick perspectives</span><div className="angle-controls">{['front','side','rear'].map(a=><button disabled={viewerStatus!=='ready'} key={a} onClick={()=>chooseAngle(a)}>{a[0].toUpperCase()+a.slice(1)}</button>)}</div></div><div className="auto-row"><label htmlFor="auto-rotate">Auto rotate</label><Switch disabled={viewerStatus!=='ready'} id="auto-rotate" checked={auto} onCheckedChange={setAuto}/></div><Link href={'/models?model='+model.id} className="button primary">Full specifications <ArrowUpRight size={17}/></Link><Link className="studio-reference" href={'/models?model='+model.id}><img src={model.image} width={model.imageWidth} height={model.imageHeight} alt={'Brochure reference for '+model.name}/><span>See the original<br/>brochure photograph ↗</span></Link><p className="studio-disclaimer">Detailed 3D recreation matched to the supplied reference photograph. Unseen surfaces remain an interpretation; use the original image for production-accurate details.</p></aside></TabsContent></Tabs><p className="source-note">Touch: drag with one finger, pinch to zoom. Keyboard: focus the viewer, then use arrow keys, + / − and Home.</p></section></>;
}
